# Generated by Django 4.2.4 on 2023-08-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(help_text='Optional: State your position. For example: teacher, student, scientist, etc..', max_length=255, null=True),
        ),
    ]
