# Generated by Django 4.2.4 on 2023-08-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Required. Enter valid email address.', max_length=254, unique=True),
        ),
    ]
