# Generated by Django 4.2.4 on 2023-08-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_article_category_alter_section_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
