# Generated by Django 4.2.4 on 2023-08-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_section_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
