# Generated by Django 4.2.4 on 2023-08-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_article_is_ready'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('article', 'number'), ('article', 'title')},
        ),
    ]
