# Generated by Django 4.2.4 on 2023-09-08 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tag_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
